// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountFiles = `-- name: AdminCountFiles :one
SELECT count(*) FROM files
`

func (q *Queries) AdminCountFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListFiles = `-- name: AdminListFiles :many
SELECT id, user_id, original_name, storage_path, mime_type, size, created_at, deleted_at FROM files ORDER BY id DESC LIMIT $1 OFFSET $2
`

type AdminListFilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) AdminListFiles(ctx context.Context, arg AdminListFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, adminListFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListFilesCursor = `-- name: AdminListFilesCursor :many
SELECT id, user_id, original_name, storage_path, mime_type, size, created_at, deleted_at FROM files
WHERE (NOT $1::boolean OR (created_at, id) < ($2::timestamptz, $3::bigint))
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type AdminListFilesCursorParams struct {
	HasCursor       bool               `json:"has_cursor"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

func (q *Queries) AdminListFilesCursor(ctx context.Context, arg AdminListFilesCursorParams) ([]File, error) {
	rows, err := q.db.Query(ctx, adminListFilesCursor,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFilesByUserID = `-- name: CountFilesByUserID :one
SELECT count(*) FROM files WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountFilesByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (user_id, original_name, storage_path, mime_type, size)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, original_name, storage_path, mime_type, size, created_at, deleted_at
`

type CreateFileParams struct {
	UserID       int64  `json:"user_id"`
	OriginalName string `json:"original_name"`
	StoragePath  string `json:"storage_path"`
	MimeType     string `json:"mime_type"`
	Size         int64  `json:"size"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.UserID,
		arg.OriginalName,
		arg.StoragePath,
		arg.MimeType,
		arg.Size,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :one
UPDATE files SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, original_name, storage_path, mime_type, size, created_at, deleted_at
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, deleteFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, original_name, storage_path, mime_type, size, created_at, deleted_at FROM files WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFilesByUserCursor = `-- name: ListFilesByUserCursor :many
SELECT id, user_id, original_name, storage_path, mime_type, size, created_at, deleted_at FROM files
WHERE user_id = $1::bigint AND deleted_at IS NULL
  AND (NOT $2::boolean OR (created_at, id) < ($3::timestamptz, $4::bigint))
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListFilesByUserCursorParams struct {
	UserID          int64              `json:"user_id"`
	HasCursor       bool               `json:"has_cursor"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

func (q *Queries) ListFilesByUserCursor(ctx context.Context, arg ListFilesByUserCursorParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByUserCursor,
		arg.UserID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByUserID = `-- name: ListFilesByUserID :many
SELECT id, user_id, original_name, storage_path, mime_type, size, created_at, deleted_at FROM files WHERE user_id = $1 AND deleted_at IS NULL ORDER BY id DESC LIMIT $2 OFFSET $3
`

type ListFilesByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFilesByUserID(ctx context.Context, arg ListFilesByUserIDParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreFile = `-- name: RestoreFile :one
UPDATE files SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, user_id, original_name, storage_path, mime_type, size, created_at, deleted_at
`

func (q *Queries) RestoreFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, restoreFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
